version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - composer install
  post_build:
    commands:
     json

artifacts:
  files:
    - '**/*'
    - 'template-configuration.json'
